### ISSUE TITLE
pane.RunCommand failure for mutli session

### ISSUE THREAD

**Issue by dc-rico** [jubnzv/go-tmux#4]
I running `func (p *Pane) RunCommand(command string) error ` is successful, when only exist one session.
But it may be failed when there is multi-session, because of can not find pane in window.
I guess `pane index` should be used in Pane.RunCommand instead of `p.ID(is pane globally unique id in reality)`， or modify command format after `-t`。
In multi-session, the value of `pane global unique id` may be beyond pane number of same window.

**Comment by jubnzv** [comment]
Hi @dc-git-git , sorry for the late response.

Is it possible to create multiple `Pane` instances in your code? I mean, each `Pane` [has](https://github.com/jubnzv/go-tmux/blob/abb245b277265885416aab04f3d3142eec2407e1/pane.go#L20) the `SessionName` attribute, which is created when initializing the `Session` instance (see [example](https://github.com/jubnzv/go-tmux/blob/abb245b277265885416aab04f3d3142eec2407e1/examples/create-session/create-session.go#L34)).

Therefore, I assume, you can create multiple sessions in your code and access their panes. Otherwise, could you please explain your use-case in more details?

**Comment by dc-rico** [comment]
Sorry for the late response and unclear statement。
My testing environment is:
I has owner a other session that create by command `tmux new -t test-session` directly。
```
$ tmux ls
test-session: 1 windows (created Mon Apr  3 16:49:17 2023)
```

Then I want running a command in pane using example code(only using one window):
Code added by me in example code:
```go
	currPane, _ := w1.ListPanes()
	fmt.Println("pance :", currPane)
	err = currPane[0].RunCommand("yes")
	if err != nil {
		fmt.Println("run command in pane 0 err: ", err)
	}
```

Here is the full code:
``` go
package main

import (
	"fmt"

	gotmux "github.com/jubnzv/go-tmux"
)

func main() {
	// Create instance of running tmux server.
	server := new(gotmux.Server)

	// Check that "example" session already exists.
	exists, err := server.HasSession("example")
	if err != nil {
		msg := fmt.Errorf("Can't check 'example' session: %s", err)
		fmt.Println(msg)
		return
	}
	if exists {
		// Sure, you can use KillSession here.
		fmt.Println("Session 'example' already exists!")
		fmt.Println("Please stop it before running this demo.")
		return
	}

	// Prepare configuration for a new session with some windows.
	session := gotmux.Session{Name: "example-session"}
	w1 := gotmux.Window{Name: "first", Id: 0}
	// w2 := gotmux.Window{Name: "second", Id: 1}
	session.AddWindow(w1)
	// session.AddWindow(w2)
	server.AddSession(session)
	sessions := []*gotmux.Session{}
	sessions = append(sessions, &session)
	conf := gotmux.Configuration{
		Server:        server,
		Sessions:      sessions,
		ActiveSession: nil}

	// Setup this configuration.
	err = conf.Apply()
	if err != nil {
		msg := fmt.Errorf("Can't apply prepared configuration: %s", err)
		fmt.Println(msg)
		return
	}

	// new add code by me
	currPane, _ := w1.ListPanes()
	fmt.Println("pance :", currPane)
	err = currPane[0].RunCommand("yes")
	if err != nil {
		fmt.Println("run command in pane 0 err: ", err)
	}

	// Attach to created session
	err = session.AttachSession()
	if err != nil {
		msg := fmt.Errorf("Can't attached to created session: %s", err)
		fmt.Println(msg)
		return
	}
}
```

When I run code, error occurred:
```
run command in pane 0 err:  exit status 1: can't find window: 63
```
Check id of tmux window and pane by command and show:
```
$ tmux list-panes -t example-session -F "#{window_index}:#{window_id}:#{pane_index}:#{pane_id}"
0:@63:0:%85
```

According to the result of `tmux list-panes ...` command。 63 is windows globally unique id, but it is used as an Index  in function `Pane.RunCommand`.

If modify id in Pane forcibly:
```
	// new add code by me
	currPane, _ := w1.ListPanes()
	fmt.Println("pance :", currPane)
	currPane[0].ID = 0       // modify id using index
	currPane[0].WindowId = 0 // modify id using index
	err = currPane[0].RunCommand("yes")
	if err != nil {
		fmt.Println("run command in pane 0 err: ", err)
	}
```

 Running code is ok. And that's exactly what I expected

So overall, I think `Id` and `Index` of pane and window is confused in function `Pane.RunCommand`。

My tmux version is `tmux 3.0a`
I using ubuntu: `Linux megvii-cp 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
Thanks.
